DATA_ROOT: "/home/oahmed6/scr4_blangme2/oahmed/doc_array/exp_2_8class"
EXP_TYPE: 2
REPO_DIRECTORY: "/home/oahmed6/docprof-experiments"
PBSIM_MODEL: "/home/oahmed6/pbsim2/data/R95.model"
RINDEX_BUILD_DIRECTORY: "/home/oahmed6/r-index_dev/build"
TIME_PROG: "/usr/bin/time"
TIME_FORMAT: "--format='user= %U system= %S elapsed= %e CPU= %P MemMax= %M'"
NUM_DATASETS_EXP1: 4
THRESHOLD_EXP1: 15
MEM_COUNT_EXP1: 1000000
NUM_DATASETS_EXP2: 8
THRESHOLD_EXP2: 0
MEM_COUNT_EXP2: 1000000